"""empty message

Revision ID: 2258e06a55a9
Revises: cb763b7f6bad
Create Date: 2021-02-04 10:09:27.179812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2258e06a55a9'
down_revision = 'cb763b7f6bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret', sa.String(), nullable=True))
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'secret')
    # ### end Alembic commands ###
