"""empty message

Revision ID: 2f058c5f55ca
Revises: c7ea47d81ff9
Create Date: 2021-02-02 10:10:06.596054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f058c5f55ca'
down_revision = 'c7ea47d81ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_title', table_name='job')
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.drop_index('ix_job_url', table_name='job')
    op.create_index(op.f('ix_job_url'), 'job', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_url'), table_name='job')
    op.create_index('ix_job_url', 'job', ['url'], unique=True)
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.create_index('ix_job_title', 'job', ['title'], unique=True)
    # ### end Alembic commands ###
