"""updating to include users

Revision ID: 98d8c6930a0b
Revises: bf0f3236a758
Create Date: 2021-02-03 18:44:41.401970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98d8c6930a0b'
down_revision = 'bf0f3236a758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('job', sa.Column('extracted_job_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('user_job_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_job_timestamp'), 'job', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'])
    op.drop_column('job', 'extracted_data')
    op.drop_column('job', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_index(op.f('ix_job_timestamp'), table_name='job')
    op.drop_column('job', 'user_job_data')
    op.drop_column('job', 'user_id')
    op.drop_column('job', 'timestamp')
    op.drop_column('job', 'extracted_job_data')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
