"""empty message

Revision ID: 99eb2fc3af47
Revises: 2f058c5f55ca
Create Date: 2021-02-02 13:28:16.007962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eb2fc3af47'
down_revision = '2f058c5f55ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('dom', sa.Text(), nullable=True))
    op.create_index(op.f('ix_job_dom'), 'job', ['dom'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_dom'), table_name='job')
    op.drop_column('job', 'dom')
    # ### end Alembic commands ###
