"""empty message

Revision ID: bf0f3236a758
Revises: fd7b480a5d21
Create Date: 2021-02-02 15:06:50.352713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf0f3236a758'
down_revision = 'fd7b480a5d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'extracted_data')
    op.drop_column('job', 'date')
    # ### end Alembic commands ###
