"""empty message

Revision ID: c7ea47d81ff9
Revises: 
Create Date: 2021-02-01 23:36:33.007619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ea47d81ff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=True)
    op.create_index(op.f('ix_job_url'), 'job', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_url'), table_name='job')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
