"""updates to the user model to take out username

Revision ID: c99a0abb81d3
Revises: 98d8c6930a0b
Create Date: 2021-02-03 19:17:40.030829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99a0abb81d3'
down_revision = '98d8c6930a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
