"""adding settings to user

Revision ID: cb763b7f6bad
Revises: c99a0abb81d3
Create Date: 2021-02-04 08:53:01.758555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb763b7f6bad'
down_revision = 'c99a0abb81d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
