"""empty message

Revision ID: e1b5a83e8a86
Revises: 99eb2fc3af47
Create Date: 2021-02-02 14:50:00.238244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b5a83e8a86'
down_revision = '99eb2fc3af47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_dom', table_name='job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_dom', 'job', ['dom'], unique=False)
    # ### end Alembic commands ###
