"""empty message

Revision ID: e81fed24b0a7
Revises: 2258e06a55a9
Create Date: 2021-02-05 13:21:28.522665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81fed24b0a7'
down_revision = '2258e06a55a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_column')
    # ### end Alembic commands ###
