"""empty message

Revision ID: fd7b480a5d21
Revises: e1b5a83e8a86
Create Date: 2021-02-02 14:53:45.812018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7b480a5d21'
down_revision = 'e1b5a83e8a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_title', table_name='job')
    op.drop_column('job', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('title', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_index('ix_job_title', 'job', ['title'], unique=False)
    # ### end Alembic commands ###
